### ISSUE TITLE
Идеи для доработки обработки "Групповая проверка доработок"

### ISSUE THREAD

**Issue by leobrn** [leobrn/ones-smoke-allure#2]
Пожелания:

1. Выбирать объекты снятые с поддержки с помощью [https://github.com/oscript-library/vanessa-support](https://github.com/oscript-library/vanessa-support)

**Comment by artbear** [comment]
Так все эти проверки есть в дымовых тестах Ванесса-АДД

Печатные формы, перезапись, открытие формы, проведение документов и т.п.

посмотри описание дымовых в каталоге tests\smoke
их очень много

**Comment by leobrn** [comment]
> Так все эти проверки есть в дымовых тестах Ванесса-АДД
> 
> Печатные формы, перезапись, открытие формы, проведение документов и т.п.
> 
> посмотри описание дымовых в каталоге tests\smoke
> их очень много

Знаю. Вариант обработкой как альтернатива. На некоторых клиентах удобнее прогнать обработкой. Для использования консультантами это проще.

**Comment by leobrn** [comment]
> Так все эти проверки есть в дымовых тестах Ванесса-АДД
> 
> Печатные формы, перезапись, открытие формы, проведение документов и т.п.
> 
> посмотри описание дымовых в каталоге tests\smoke
> их очень много

Ещё есть проблема , когда клиенты против установки различного по (oscript, allure и т.д).
Есть клиенты с серверами , которые оставляют желать лучшего и дымовые через менеджер+клиент тестирования работают очень долго, даже если настроить фильтры.

А есть такие с которыми работаешь только через анидеск/тимвивер))

Я пока такие кейсы закрываю обработкой. Стараюсь, чтобы тестирование было в любых случаях. Буду рад , если поделитесь опытом
